services:
  auth_db:
    image: postgres:16.3-alpine3.19
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
