services:
  db:
    image: postgres:16.3-alpine3.19
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  db_data:
